name: Cypress Tests

on:
  push:
    branches:
      - main  # Execute na branch 'main'
  pull_request:
    branches:
      - main  # Execute para pull requests na branch 'main'

jobs:
  # Job para rodar testes de FrontEnd
  frontend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Faz o checkout do repositório

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Configura o Node.js (versão 14)

      - name: Install dependencies
        run: npm install  # Instala as dependências do Cypress e demais pacotes

      - name: Run FrontEnd Cypress tests
        run: npm run cypress:run --spec "cypress/e2e/pages/FrontEnd/*.spec.js"  # Rodar os testes do FrontEnd
        env:
          CYPRESS_BASE_URL: 'https://www.saucedemo.com'  # Define a URL base da aplicação

  # Job para rodar testes de BackEnd (API)
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run BackEnd Cypress API tests
        run: npm run cypress:run --spec "cypress/e2e/pages/Backend/*.spec.js"  # Rodar os testes de API
